import { createHash } from 'node:crypto'
import { mkdir, readFile, unlink, writeFile } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import { S3Client, DeleteObjectCommand, PutObjectCommand } from '@aws-sdk/client-s3'

/**
 * P-07 -- object storage.
 *
 * Two drivers behind one interface: Cloudflare R2 in production (zero egress fees, which
 * is what keeps image bandwidth off the P&L), and the local filesystem in development so
 * the whole upload path is exercisable without credentials.
 */
export interface StoredObject {
  key: string
  url: string
  bytes: number
}

export interface Storage {
  put(key: string, body: Buffer, contentType: string): Promise<StoredObject>
  delete(key: string): Promise<void>
  /** Local driver only; R2 objects are served by Cloudflare, not by us. */
  read?(key: string): Promise<Buffer | null>
  readonly kind: 'r2' | 'local'
}

class R2Storage implements Storage {
  readonly kind = 'r2' as const
  private client: S3Client
  constructor(
    private bucket: string,
    private publicBase: string,
    accountId: string,
    accessKeyId: string,
    secretAccessKey: string,
  ) {
    this.client = new S3Client({
      region: 'auto',
      endpoint: `https://${accountId}.r2.cloudflarestorage.com`,
      credentials: { accessKeyId, secretAccessKey },
    })
  }

  async put(key: string, body: Buffer, contentType: string): Promise<StoredObject> {
    await this.client.send(
      new PutObjectCommand({
        Bucket: this.bucket,
        Key: key,
        Body: body,
        ContentType: contentType,
        // Content is immutable: the key contains a content hash, so a changed image is
        // a different key and this can be cached forever.
        CacheControl: 'public, max-age=31536000, immutable',
      }),
    )
    return { key, url: `${this.publicBase}/${key}`, bytes: body.byteLength }
  }

  async delete(key: string): Promise<void> {
    await this.client.send(new DeleteObjectCommand({ Bucket: this.bucket, Key: key }))
  }
}

class LocalStorage implements Storage {
  readonly kind = 'local' as const
  constructor(
    private root: string,
    private publicBase: string,
  ) {}

  private path(key: string): string {
    // Resolve and confirm containment: a key with ../ in it would otherwise write
    // anywhere on disk. Keys are generated by us, but this is a filesystem write.
    const full = resolve(join(this.root, key))
    if (!full.startsWith(resolve(this.root) + '/')) throw new Error('Invalid storage key.')
    return full
  }

  async put(key: string, body: Buffer, _contentType: string): Promise<StoredObject> {
    const full = this.path(key)
    await mkdir(dirname(full), { recursive: true })
    await writeFile(full, body)
    return { key, url: `${this.publicBase}/${key}`, bytes: body.byteLength }
  }

  async delete(key: string): Promise<void> {
    await unlink(this.path(key)).catch(() => {})
  }

  async read(key: string): Promise<Buffer | null> {
    return readFile(this.path(key)).catch(() => null)
  }
}

let cached: Storage | null = null

export function storage(): Storage {
  if (cached) return cached
  const { R2_ACCOUNT_ID, R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY, R2_BUCKET, CDN_BASE_URL } = process.env

  if (R2_ACCOUNT_ID && R2_ACCESS_KEY_ID && R2_SECRET_ACCESS_KEY && R2_BUCKET) {
    cached = new R2Storage(
      R2_BUCKET,
      CDN_BASE_URL ?? `https://${R2_BUCKET}.r2.dev`,
      R2_ACCOUNT_ID,
      R2_ACCESS_KEY_ID,
      R2_SECRET_ACCESS_KEY,
    )
  } else {
    // Absolute, via env, because the dashboard and the renderer run as separate
    // processes with different working directories. A cwd-relative default silently
    // gives them two different stores, and an uploaded image never appears on the site.
    cached = new LocalStorage(
      process.env.LOCAL_STORAGE_DIR ?? resolve(process.cwd(), '.storage'),
      process.env.CDN_BASE_URL ?? '/asset',
    )
  }
  return cached
}

export function __setStorage(s: Storage | null): void {
  cached = s
}

/**
 * Content-addressed keys. The same image uploaded twice lands on the same key, which
 * deduplicates storage and makes every object safe to cache forever.
 */
export function assetKey(siteId: string, body: Buffer, ext: string): string {
  const hash = createHash('sha256').update(body).digest('hex').slice(0, 24)
  return `sites/${siteId}/${hash}.${ext}`
}

/**
 * The identifier a spec uses to reference an asset.
 *
 * Derived from the row's uuid rather than being a second independent id: site_assets.id
 * is a uuid primary key with product_images pointing at it, and a parallel identifier
 * would mean two things to keep in step. A uuid's hex is 32 alphanumeric characters,
 * which satisfies the spec's `asset_[a-zA-Z0-9]{8,}` shape exactly.
 */
export function assetIdFor(uuid: string): string {
  return `asset_${uuid.replace(/-/g, '')}`
}

/** The inverse. Returns null for a stock: id or anything malformed. */
export function assetUuidFrom(assetId: string): string | null {
  const m = /^asset_([0-9a-f]{32})$/i.exec(assetId)
  if (!m) return null
  const h = m[1]!
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-${h.slice(12, 16)}-${h.slice(16, 20)}-${h.slice(20)}`
}
