import { createHash } from 'node:crypto'
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

/**
 * O-05b -- compile the legal documents into a module.
 *
 * The .md files in docs/legal are what a lawyer edits. This turns them into something
 * the application can serve and, more importantly, hash: acceptance is recorded against
 * the hash, so it is always possible to show exactly which words a customer agreed to.
 * Editing a document afterwards does not quietly rewrite what they accepted.
 *
 * Same arrangement as the spec catalogue: generated, committed, and CI fails if stale.
 */
const SRC = join(import.meta.dirname, '..', 'docs', 'legal')
const OUT = join(import.meta.dirname, '..', 'packages', 'api', 'src', 'legal', 'generated.ts')

/** Documents shown to customers. README and the lawyer brief are internal. */
const PUBLISHED = ['TERMS.md', 'ACCEPTABLE-USE.md', 'SUBPROCESSORS.md']

interface Parsed { id: string; title: string; version: number; body: string; sha256: string }

function parse(file: string): Parsed {
  const raw = readFileSync(join(SRC, file), 'utf8')
  const m = /^---\n([\s\S]*?)\n---\n([\s\S]*)$/.exec(raw)
  if (!m) throw new Error(`${file}: missing front matter`)
  const [, fm, body] = m
  const field = (k: string): string => {
    const v = new RegExp(`^${k}:\\s*(.+)$`, 'm').exec(fm!)?.[1]?.trim()
    if (!v) throw new Error(`${file}: front matter is missing "${k}"`)
    return v
  }
  const version = Number(field('version'))
  if (!Number.isInteger(version) || version < 1) throw new Error(`${file}: version must be a positive integer`)

  const text = body!.trim()
  return {
    id: field('id'),
    title: field('title'),
    version,
    body: text,
    // Hash the text only. Changing the effective date must not invalidate consent
    // already given to identical wording.
    sha256: createHash('sha256').update(text, 'utf8').digest('hex'),
  }
}

const docs = PUBLISHED.map(parse)
const missing = readdirSync(SRC).filter((f) => f.endsWith('.md') && !PUBLISHED.includes(f))

const ids = new Set(docs.map((d) => d.id))
if (ids.size !== docs.length) throw new Error('two documents share an id')

writeFileSync(
  OUT,
  `// GENERATED by scripts/gen-legal.ts from docs/legal/*.md — do not edit.
// Run \`pnpm gen:legal\` after changing a document.
//
// Internal, not served: ${missing.join(', ') || 'none'}

export interface LegalDocument {
  id: string
  title: string
  /** Bumped by hand for a MATERIAL change. That is what forces re-acceptance. */
  version: number
  /** SHA-256 of the body text, so we can prove which words were accepted. */
  sha256: string
  body: string
}

export const LEGAL_DOCUMENTS: readonly LegalDocument[] = ${JSON.stringify(docs, null, 2)} as const

export const DOCUMENT_IDS = LEGAL_DOCUMENTS.map((d) => d.id)

export function legalDocument(id: string): LegalDocument | undefined {
  return LEGAL_DOCUMENTS.find((d) => d.id === id)
}
`,
)
console.log(`legal: ${docs.length} documents compiled`)
for (const d of docs) console.log(`  ${d.id} v${d.version}  ${d.sha256.slice(0, 12)}  ${d.body.length} chars`)
